# Automatically generated by: ros2nix --nixfmt --distro noetic --fetch --output-dir ../nix/carla-ros-bridge --output-as-nix-pkg-name
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  catkin,
  diagnostic-msgs,
  geometry-msgs,
  message-generation,
  message-runtime,
  ros-environment,
  std-msgs,
}:
buildRosPackage rec {
  pname = "ros-noetic-carla-msgs";
  version = "1.3.0";

  src = fetchFromGitHub {
    owner = "carla-simulator";
    repo = "ros-carla-msgs";
    rev = "081fdcdc8a4f8d4ce936b792c4ef13aba3fd7478";
    sha256 = "1cd6psvkcpg6agrbrpjjhlzi9rfbfybn977kpps5pybfjkm2cf1m";
  };

  buildType = "catkin";
  buildInputs = [
    catkin
    message-generation
    ros-environment
  ];
  propagatedBuildInputs = [
    diagnostic-msgs
    geometry-msgs
    message-runtime
    std-msgs
  ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = "The carla_msgs package";
    license = with lib.licenses; [ mit ];
  };
}
