# Automatically generated by: ros2nix --nixfmt --distro noetic --fetch --output-dir ../nix/carla-ros-bridge --output-as-nix-pkg-name
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  carla-ad-agent,
  carla-manual-control,
  carla-ros-bridge,
  carla-ros-scenario-runner,
  carla-spawn-objects,
  carla-twist-to-control,
  carla-waypoint-publisher,
  catkin,
  rostopic,
  rviz,
  rviz-carla-plugin,
}:
buildRosPackage rec {
  pname = "ros-noetic-carla-ad-demo";
  version = "0.0.1";

  src = fetchFromGitHub {
    owner = "carla-simulator";
    repo = "ros-bridge";
    rev = "e9063d97ff5a724f76adbb1b852dc71da1dcfeec";
    sha256 = "1zfmsgr9xiaj45mvjxjdfklwpy8yipjqsicgr5qxnlazzzhr5nmk";
  };

  buildType = "catkin";
  sourceRoot = "${src.name}/carla_ad_demo/";
  buildInputs = [ catkin ];
  propagatedBuildInputs = [
    carla-ad-agent
    carla-manual-control
    carla-ros-bridge
    carla-ros-scenario-runner
    carla-spawn-objects
    carla-twist-to-control
    carla-waypoint-publisher
    rostopic
    rviz
    rviz-carla-plugin
  ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = "The carla_ad_demo package";
    license = with lib.licenses; [ mit ];
  };
}
