# Automatically generated by: ros2nix --nixfmt --distro noetic --fetch --output-dir ../nix/carla-ros-bridge --output-as-nix-pkg-name
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  catkin,
  message-generation,
  message-runtime,
  nav-msgs,
  ros-environment,
}:
buildRosPackage rec {
  pname = "ros-noetic-carla-waypoint-types";
  version = "0.1.0";

  src = fetchFromGitHub {
    owner = "carla-simulator";
    repo = "ros-bridge";
    rev = "e9063d97ff5a724f76adbb1b852dc71da1dcfeec";
    sha256 = "1zfmsgr9xiaj45mvjxjdfklwpy8yipjqsicgr5qxnlazzzhr5nmk";
  };

  buildType = "catkin";
  sourceRoot = "${src.name}/carla_waypoint_types/";
  buildInputs = [
    catkin
    message-generation
    ros-environment
  ];
  propagatedBuildInputs = [
    message-runtime
    nav-msgs
  ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = "The carla_waypoint_types package";
    license = with lib.licenses; [ mit ];
  };
}
