# Automatically generated by: ros2nix --nixfmt --distro noetic --fetch --output-dir ../nix/carla-ros-bridge --output-as-nix-pkg-name
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  carla-waypoint-types,
  catkin,
  nav-msgs,
  ros-compatibility,
  roslaunch,
  rospy,
}:
buildRosPackage rec {
  pname = "ros-noetic-carla-waypoint-publisher";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "carla-simulator";
    repo = "ros-bridge";
    rev = "e9063d97ff5a724f76adbb1b852dc71da1dcfeec";
    sha256 = "1zfmsgr9xiaj45mvjxjdfklwpy8yipjqsicgr5qxnlazzzhr5nmk";
  };

  buildType = "catkin";
  sourceRoot = "${src.name}/carla_waypoint_publisher/";
  buildInputs = [
    catkin
    roslaunch
  ];
  propagatedBuildInputs = [
    carla-waypoint-types
    nav-msgs
    ros-compatibility
    rospy
  ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = "The carla_waypoint_publisher package";
    license = with lib.licenses; [ mit ];
  };
}
