# Automatically generated by: ros2nix --nixfmt --distro noetic --fetch --output-dir ../nix/carla-ros-bridge --output-as-nix-pkg-name
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  carla-msgs,
  carla-waypoint-types,
  catkin,
  ros-compatibility,
  roslaunch,
  rospy,
  topic-tools,
}:
buildRosPackage rec {
  pname = "ros-noetic-carla-ad-agent";
  version = "0.0.1";

  src = fetchFromGitHub {
    owner = "carla-simulator";
    repo = "ros-bridge";
    rev = "e9063d97ff5a724f76adbb1b852dc71da1dcfeec";
    sha256 = "1zfmsgr9xiaj45mvjxjdfklwpy8yipjqsicgr5qxnlazzzhr5nmk";
  };

  buildType = "catkin";
  sourceRoot = "${src.name}/carla_ad_agent/";
  buildInputs = [
    catkin
    roslaunch
  ];
  propagatedBuildInputs = [
    carla-msgs
    carla-waypoint-types
    ros-compatibility
    rospy
    topic-tools
  ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = "The carla_ad_agent package";
    license = with lib.licenses; [ mit ];
  };
}
