# Automatically generated by: ros2nix --nixfmt --distro noetic --fetch --output-dir ../nix/carla-ros-bridge --output-as-nix-pkg-name
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  carla-ros-bridge,
  catkin,
  pcl-conversions,
  pcl-ros,
  roscpp,
  roslaunch,
  rostopic,
  sensor-msgs,
}:
buildRosPackage rec {
  pname = "ros-noetic-pcl-recorder";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "carla-simulator";
    repo = "ros-bridge";
    rev = "e9063d97ff5a724f76adbb1b852dc71da1dcfeec";
    sha256 = "1zfmsgr9xiaj45mvjxjdfklwpy8yipjqsicgr5qxnlazzzhr5nmk";
  };

  buildType = "catkin";
  sourceRoot = "${src.name}/pcl_recorder/";
  buildInputs = [
    catkin
    roslaunch
  ];
  propagatedBuildInputs = [
    carla-ros-bridge
    pcl-conversions
    pcl-ros
    roscpp
    rostopic
    sensor-msgs
  ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = "The pcl_recorder package";
    license = with lib.licenses; [ mit ];
  };
}
