# Automatically generated by: ros2nix --nixfmt --distro noetic --fetch --output-dir ../nix/carla-ros-bridge --output-as-nix-pkg-name
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  catkin,
  rospy,
  std-msgs, python3Packages,
}:
buildRosPackage rec {
  pname = "ros-noetic-ros-compatibility";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "carla-simulator";
    repo = "ros-bridge";
    rev = "e9063d97ff5a724f76adbb1b852dc71da1dcfeec";
    sha256 = "1zfmsgr9xiaj45mvjxjdfklwpy8yipjqsicgr5qxnlazzzhr5nmk";
  };

  buildType = "catkin";
  sourceRoot = "${src.name}/ros_compatibility/";
  buildInputs = [
    catkin
    python3Packages.distutils
  ];
  propagatedBuildInputs = [
    rospy
    std-msgs
  ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = "The ros_compatibility package";
    license = with lib.licenses; [ mit ];
  };
}
