# Automatically generated by: ros2nix --nixfmt --distro noetic --fetch --output-dir ../nix/carla-ros-bridge --output-as-nix-pkg-name
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  catkin,
  python-qt-binding,
  rospy,
  rqt-gui-py,
}:
buildRosPackage rec {
  pname = "ros-noetic-rqt-carla-control";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "carla-simulator";
    repo = "ros-bridge";
    rev = "e9063d97ff5a724f76adbb1b852dc71da1dcfeec";
    sha256 = "1zfmsgr9xiaj45mvjxjdfklwpy8yipjqsicgr5qxnlazzzhr5nmk";
  };

  buildType = "catkin";
  sourceRoot = "${src.name}/rqt_carla_control/";
  buildInputs = [ catkin ];
  propagatedBuildInputs = [
    python-qt-binding
    rospy
    rqt-gui-py
  ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = "The rqt_carla_control package";
    license = with lib.licenses; [ mit ];
  };
}
