# Automatically generated by: ros2nix --nixfmt --distro noetic --fetch --output-dir ../nix/carla-ros-bridge --output-as-nix-pkg-name
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  carla-msgs,
  carla-ros-scenario-runner-types,
  catkin,
  geometry-msgs,
  nav-msgs,
  qt5,
  rviz,
  tf2-geometry-msgs,
}:
buildRosPackage rec {
  pname = "ros-noetic-rviz-carla-plugin";
  version = "0.0.1";

  src = fetchFromGitHub {
    owner = "carla-simulator";
    repo = "ros-bridge";
    rev = "e9063d97ff5a724f76adbb1b852dc71da1dcfeec";
    sha256 = "1zfmsgr9xiaj45mvjxjdfklwpy8yipjqsicgr5qxnlazzzhr5nmk";
  };

  buildType = "catkin";
  sourceRoot = "${src.name}/rviz_carla_plugin/";
  buildInputs = [
    catkin
    tf2-geometry-msgs
  ];
  propagatedBuildInputs = [
    carla-msgs
    carla-ros-scenario-runner-types
    geometry-msgs
    nav-msgs
    qt5.qtbase
    rviz
  ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = "The carla_ros_bridge package";
    license = with lib.licenses; [ mit ];
  };
}
